server:
  port: 3000
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  config:
    import: optional:file:.env[.properties]
  main:
    allow-bean-definition-overriding: true

app:
  redis:
    host: localhost
    port: 6379
  cache:
    cacheType: redis
    caches:
      taskAfterCreate:
        ttl: 5m
      taskAfterUpdate:
        ttl: 10m
      taskList:
        ttl: 10m


